CREATE TABLE BenhNhan
(
  MaBenhNhan CHAR(7) NOT NULL,
  HoTen NVARCHAR(255) NOT NULL,
  GioiTinh NVARCHAR(10) NOT NULL,
  NgaySinh DATE NOT NULL,
  DiaChi NVARCHAR(255) NOT NULL,
  SDT CHAR(10) NOT NULL,
  PRIMARY KEY (MaBenhNhan)
);

CREATE TABLE DichVu
(
  MaDichVu CHAR(7) NOT NULL,
  TenDichVu NVARCHAR(255) NOT NULL,
  DonGia FLOAT NOT NULL,
  DonViTinh NVARCHAR(10) NOT NULL,
  GhiChu NVARCHAR(255) NOT NULL,
  SoLanSuDung INT NOT NULL,
  PRIMARY KEY (MaDichVu)
);

CREATE TABLE TaiKhoan
(
  TenDangNhap CHAR(7) NOT NULL,
  MatKhau VARCHAR(255) NOT NULL,
  QuyenTruyCap INT NOT NULL,
  TrangThai INT NOT NULL,
  PRIMARY KEY (TenDangNhap)
);

CREATE TABLE Benh
(
  MaBenh CHAR(7) NOT NULL,
  LoaiBenh NVARCHAR(255) NOT NULL,
  MoTaBenh NVARCHAR(1000) NOT NULL,
  PRIMARY KEY (MaBenh)
);

CREATE TABLE NhanVien
(
  MaNhanVien CHAR(7) NOT NULL,
  HoTen NVARCHAR(255) NOT NULL,
  GioiTinh NVARCHAR(10) NOT NULL,
  ChucVu NVARCHAR(20) NOT NULL,
  DiaChi NVARCHAR(255) NOT NULL,
  SDT CHAR(10) NOT NULL,
  PRIMARY KEY (MaNhanVien),
  FOREIGN KEY (MaNhanVien) REFERENCES TaiKhoan(TenDangNhap)
);

CREATE TABLE BacSi
(
  MaBacSi CHAR(7) NOT NULL,
  HoTen NVARCHAR(255) NOT NULL,
  GioiTinh NVARCHAR(10) NOT NULL,
  TrinhDo NVARCHAR(20) NOT NULL,
  ChucVu NVARCHAR(20) NOT NULL,
  DiaChi NVARCHAR(255) NOT NULL,
  SDT CHAR(10) NOT NULL,
  PRIMARY KEY (MaBacSi),
  FOREIGN KEY (MaBacSi) REFERENCES TaiKhoan(TenDangNhap)
);

CREATE TABLE BanKe
(
  MaBanKe CHAR(10) NOT NULL,
  NgayLapBanKe DATE NOT NULL,
  MaBenhNhan CHAR(7) NOT NULL,
  MaNhanVien CHAR(7) NOT NULL,
  PRIMARY KEY (MaBanKe),
  FOREIGN KEY (MaBenhNhan) REFERENCES BenhNhan(MaBenhNhan),
  FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien)
);

CREATE TABLE ChiTietBanKe
(
  MaBanKe CHAR(10) NOT NULL,
  MaDichVu CHAR(7) NOT NULL,
  SoLuong INT NOT NULL,
  PRIMARY KEY (MaBanKe, MaDichVu),
  FOREIGN KEY (MaBanKe) REFERENCES BanKe(MaBanKe),
  FOREIGN KEY (MaDichVu) REFERENCES DichVu(MaDichVu)
);

CREATE TABLE HoSoBenhAn
(
  SoBenhAn CHAR(10) NOT NULL,
  MaBenhNhan CHAR(7) NOT NULL,
  MaBenh CHAR(7) NOT NULL,
  MaBacSi CHAR(7) NOT NULL,
  NgayKham DATE NOT NULL,
  ChanDoan NVARCHAR(1000) NOT NULL,
  PRIMARY KEY (SoBenhAn),
  FOREIGN KEY (MaBenhNhan) REFERENCES BenhNhan(MaBenhNhan),
  FOREIGN KEY (MaBenh) REFERENCES Benh(MaBenh),
  FOREIGN KEY (MaBacSi) REFERENCES BacSi(MaBacSi)
);

CREATE TABLE PhieuThuTienTamUng
(
  MaPhieuThuTienTamUng CHAR(10) NOT NULL,
  SoTienThuTamUng FLOAT NOT NULL,
  NgayThuTienTamUng DATE NOT NULL,
  MaBanKe CHAR(10) NOT NULL,
  MaNhanVien CHAR(7) NOT NULL,
  PRIMARY KEY (MaPhieuThuTienTamUng),
  FOREIGN KEY (MaBanKe) REFERENCES BanKe(MaBanKe),
  FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien)
);

CREATE TABLE KetQuaXetNghiem
(
  MaBanKe CHAR(10) NOT NULL,
  MaDichVu CHAR(7) NOT NULL,
  MaBacSi CHAR(7) NOT NULL,
  NgayKham DATE NOT NULL,
  KetQua NVARCHAR(1000) NOT NULL,
  PRIMARY KEY (MaBanKe, MaDichVu, MaBacSi),
  FOREIGN KEY (MaBanKe, MaDichVu) REFERENCES ChiTietBanKe(MaBanKe, MaDichVu),
  FOREIGN KEY (MaBacSi) REFERENCES BacSi(MaBacSi)
);

CREATE TABLE TongHopChiPhi
(
  MaHoaDon CHAR(10) NOT NULL,
  MaPhieuThuTienTamUng CHAR(10) NOT NULL,
  MaNhanVien CHAR(7) NOT NULL,
  ThanhTien FLOAT NOT NULL,
  NgayThanhToan DATE NOT NULL,
  PRIMARY KEY (MaHoaDon),
  FOREIGN KEY (MaPhieuThuTienTamUng) REFERENCES PhieuThuTienTamUng(MaPhieuThuTienTamUng),
  FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien)
);

INSERT INTO TaiKhoan (TenDangNhap, MatKhau, QuyenTruyCap)
VALUES ('admin','123',0);
